I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 209, in script
    python:
  File "renpy/common/00start.rpy", line 213, in <module>
    renpy.call_in_new_context("_main_menu")
  File "renpy/common/00action_file.rpy", line 347, in __call__
    renpy.load(fn)
AttributeError: 'ImageReference' object has no attribute 'after_upgrade'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\renpy-6.17.7-sdk\renpy\bootstrap.py", line 281, in bootstrap
    renpy.main.main()
  File "D:\renpy-6.17.7-sdk\renpy\main.py", line 468, in main
    run(restart)
  File "D:\renpy-6.17.7-sdk\renpy\main.py", line 139, in run
    renpy.execution.run_context(True)
  File "D:\renpy-6.17.7-sdk\renpy\execution.py", line 714, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 209, in script
    python:
  File "D:\renpy-6.17.7-sdk\renpy\ast.py", line 805, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy-6.17.7-sdk\renpy\python.py", line 1461, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00start.rpy", line 213, in <module>
    renpy.call_in_new_context("_main_menu")
  File "D:\renpy-6.17.7-sdk\renpy\game.py", line 313, in call_in_new_context
    return renpy.execution.run_context(False)
  File "D:\renpy-6.17.7-sdk\renpy\execution.py", line 714, in run_context
    context.run()
  File "renpy/common/_layout/screen_main_menu.rpym", line 29, in script
    $ ui.interact()
  File "D:\renpy-6.17.7-sdk\renpy\ast.py", line 805, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy-6.17.7-sdk\renpy\python.py", line 1461, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/_layout/screen_main_menu.rpym", line 29, in <module>
    $ ui.interact()
  File "D:\renpy-6.17.7-sdk\renpy\ui.py", line 277, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\renpy-6.17.7-sdk\renpy\display\core.py", line 2424, in interact
    repeat, rv = self.interact_core(preloads=preloads, **kwargs)
  File "D:\renpy-6.17.7-sdk\renpy\display\core.py", line 3080, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "D:\renpy-6.17.7-sdk\renpy\display\layout.py", line 906, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "D:\renpy-6.17.7-sdk\renpy\display\transition.py", line 45, in event
    return self.new_widget.event(ev, x, y, st) # E1101
  File "D:\renpy-6.17.7-sdk\renpy\display\layout.py", line 906, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "D:\renpy-6.17.7-sdk\renpy\display\layout.py", line 906, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "D:\renpy-6.17.7-sdk\renpy\display\screen.py", line 638, in event
    rv = self.child.event(ev, x, y, st)
  File "D:\renpy-6.17.7-sdk\renpy\display\layout.py", line 906, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "D:\renpy-6.17.7-sdk\renpy\display\behavior.py", line 811, in event
    return handle_click(self.clicked)
  File "D:\renpy-6.17.7-sdk\renpy\display\behavior.py", line 754, in handle_click
    rv = run(action)
  File "D:\renpy-6.17.7-sdk\renpy\display\behavior.py", line 295, in run
    return var(*args, **kwargs)
  File "renpy/common/00action_file.rpy", line 347, in __call__
    renpy.load(fn)
  File "D:\renpy-6.17.7-sdk\renpy\loadsave.py", line 579, in load
    roots, log = loads(location.load(filename))
  File "D:\renpy-6.17.7-sdk\renpy\loadsave.py", line 49, in loads
    return cPickle.loads(s)
  File "D:\renpy-6.17.7-sdk\renpy\object.py", line 54, in __setstate__
    self.after_upgrade(version) # E1101
AttributeError: 'ImageReference' object has no attribute 'after_upgrade'

Windows-8-6.2.9200
Ren'Py 6.99.8.959
b_l_a_m_e 0.0
